### ISSUE TITLE
Add extra slim footer option

### ISSUE THREAD

**Issue by line47** [18F/uswds-jekyll#101]
Similar to how the header component is used build a footer component similar to https://login.gov/

The slim footer should just contain links and a logo/agency name

### Screenshot
![screen shot 2018-01-16 at 10 19 33 am](https://user-images.githubusercontent.com/1449852/34996106-93d6c202-faa6-11e7-82ca-6432401de74a.png)

**Comment by afeld** [comment]
Closing as part of https://github.com/18F/uswds-jekyll/issues/190.
