### ISSUE TITLE
Include Help Wanted issues on Code.gov

### ISSUE THREAD

**Issue by jcastle** [18F/uswds-jekyll#115]
It looks like you have quite a few Help Wanted issues in your repo.  You can feature these on Code.gov and reach a larger audience by adding specific tags to your Help Wanted issues.  

Here are the specifics - https://github.com/GSA/code-gov/blob/master/HelpWanted.md
And, an example - https://github.com/GSA/code-gov-web/issues/417

Let me know if you have questions, 
Cheers!
Joe

**Comment by line47** [comment]
👋 Hey @jcastle I took a shot at setting up our first issue for code.gov if you have a few moments to take a look and offer any thoughts that would be helpful, thanks!

https://github.com/18F/uswds-jekyll/issues/53

**Comment by afeld** [comment]
No longer applicable.
