### ISSUE TITLE
Add optional logo to header.yml

### ISSUE THREAD

**Issue by line47** [18F/uswds-jekyll#124]
**Issue Description:**
Add the ability to specify a header logo image in the `header.yml` data file with a URL. https://github.com/18F/uswds-jekyll/blob/master/_data/header.yml

Adding a logo should be optional and if not wanted could be commented out from `header.yml`.

See https://oes.gsa.gov/ for an example of a logo in the header and see the following component guide for the different header types https://components.designsystem.digital.gov/components/detail/header--default.html

**Comment by eddietejeda** [comment]
Hi @rahearn, what's the status on this?

**Comment by rahearn** [comment]
@eddietejeda I wasn't able to merge #170 until it had an approving review. Merged now.
