### ISSUE TITLE
Add spacing for multiple logos in footer 

### ISSUE THREAD

**Issue by line47** [18F/uswds-jekyll#127]
When you add multiple logos into the footer their is no spacing between the logos. 
Add some spacing when multiple logos are used.

**Comment by heatherdesigns** [comment]
Hello! :wave: 
I'm checking in to see if this is still an issue. If so, may I take a stab at it? I'm looking for ways to contribute for Hacktoberfest.
Thanks!
Heather

**Comment by afeld** [comment]
Closing as part of https://github.com/18F/uswds-jekyll/issues/190.
