### ISSUE TITLE
Add team and project layouts

### ISSUE THREAD

**Issue by line47** [18F/uswds-jekyll#128]
Adding new layouts for team and project listings as well as individual project and team member pages.

**The previews**

- [Project preview](https://federalist-proxy.app.cloud.gov/preview/18f/uswds-jekyll/sw-teams-and-projects/projects/)
- [Team preview](https://federalist-proxy.app.cloud.gov/preview/18f/uswds-jekyll/sw-teams-and-projects/team/)

**The layouts (Jekyll)** 
- [Project layout](https://github.com/18F/uswds-jekyll/blob/sw-teams-and-projects/_layouts/project.html)
- [Team-member layout](https://github.com/18F/uswds-jekyll/blob/sw-teams-and-projects/_layouts/team-member.html)

**The includes (Jekyll)** 
- [Project list include](https://github.com/18F/uswds-jekyll/blob/sw-teams-and-projects/_includes/project-list.html)
- [Team list include](https://github.com/18F/uswds-jekyll/blob/sw-teams-and-projects/_includes/team-list.html)

**The project and team collections (Jekyll)**
- [Project collection](https://github.com/18F/uswds-jekyll/tree/sw-teams-and-projects/_projects)
- [Team collection](https://github.com/18F/uswds-jekyll/tree/sw-teams-and-projects/_team)

**Comment by maya** [comment]
I'd adjust the card design to look like this (except all the buttons should be aligned on the bottom like here https://oes.gsa.gov/work/) 

This is with 2rem of spacing.

<img width="1014" alt="screen shot 2018-02-22 at 10 39 13 am" src="https://user-images.githubusercontent.com/5249443/36557314-ca05a536-17bc-11e8-99bf-e815dcc1d4d3.png">

**Comment by maya** [comment]
Also, the buttons should be text links (use a similar style to OES and the 18F site).

**Comment by tbaxter-18f** [comment]
those buttons (helpfully displayed by @maya) are appearing disconnected to their parent in some cases, particuarly if there's a short summary. At a glance, they appear more connected with the next item below. Is there any way we can improve their connection to their parent, or improve their separation from the next item? Just changing them to links may do it....

**Comment by line47** [comment]
Thanks @maya and @tbaxter-18f !

Updated screenshot
![screen shot 2018-02-22 at 2 08 47 pm](https://user-images.githubusercontent.com/1449852/36558748-03b4bdfe-17da-11e8-9101-2d3223c183cf.png)
