### ISSUE TITLE
Chris (the Communicator), needs to be able to pick a template or theme that addresses his agency goal's and his agency's users' goals.

### ISSUE THREAD

**Issue by austinhernandez** [18F/uswds-jekyll#153]
Follow on work from #122: Provide our persona Chris the Communicator with guidance on how to use the color palettes. 

[Text for providing guidance is here](
https://drive.google.com/open?id=1TqpmbYlRjFgjfPNBB4CgBUHFZ1kLEr8o0puuckJuBdU)

## Draft: this will need some UX and Design work:

Guide to selecting your color palette:
![themes page-federalist 2](https://user-images.githubusercontent.com/23194720/38111305-76670160-336c-11e8-857f-91b07fe8f607.png)

Edits to the Template page: 
![templates-themes page-federalist](https://user-images.githubusercontent.com/23194720/38111335-948c5082-336c-11e8-9458-ed042cd3f1b1.png)

**Comment by austinhernandez** [comment]
Next steps:
- [Text and moods to support each theme WIP](https://docs.google.com/document/d/1Hoc7K_W9_Xz2YlGhaVRVIvIifdzmX5RJ6VIXACVSjDY/edit?usp=sharing)
- [Stock photography to support each theme WIP](https://docs.google.com/document/d/1Hoc7K_W9_Xz2YlGhaVRVIvIifdzmX5RJ6VIXACVSjDY/edit?usp=sharing)
- Task flow of selecting a template and design 
  - Rough pages here above
- Education around visual design best-practices
  - Rough pages here above, [link to best-practices guidance document here](https://docs.google.com/document/d/1TqpmbYlRjFgjfPNBB4CgBUHFZ1kLEr8o0puuckJuBdU/edit)

**Comment by wslack** [comment]
Next things that need to happen:

Implement live examples/prototypes of these
Create/document a mechanism to use them

**Comment by afeld** [comment]
Closing as part of https://github.com/18F/uswds-jekyll/issues/190.
