### ISSUE TITLE
use grid for layout?

### ISSUE THREAD

**Issue by afeld** [18F/uswds-jekyll#157]
I was surprised to find that while there is `usa-grid` class on the `main-content`, USWDS grid classes aren't actually being used for layout of the sidebar/pages. @line47 Is there a specific reason?

**Comment by line47** [comment]
That's a good catch, the reason the grid is not being used on the pages with sidebar is because the grid was switching the layout to mobile at breakpoints that were not optimal. Taken from something similar for the side nav of the USWDS site https://designsystem.digital.gov/components/

**Comment by afeld** [comment]
Today I Learned about CSS `calc()`!

![screen shot 2018-06-07 at 1 31 42 pm](https://user-images.githubusercontent.com/86842/41118484-1b1b34d8-6a5e-11e8-93d9-36d571eff738.png)

Anyway, weird that the [sidenav "compare" example](https://components.designsystem.digital.gov/components/detail/sidenav--compare.html) uses the grid, while the components page itself `calc()`ulates the width on its own. Curious to hear what the USWDS team recommends.

cc https://github.com/uswds/uswds/issues/1745

**Comment by afeld** [comment]
This project is in maintenance mode, so closing.
