### ISSUE TITLE
Explore updates for USWDS 2.0 

### ISSUE THREAD

**Issue by line47** [18F/uswds-jekyll#171]
What would it take to update to USWDS 2.0?

**Comment by anweiss** [comment]
Any updates on this? Any timelines for getting this updated to 2.0?

**Comment by rahearn** [comment]
I don't believe any work has been undertaken. Now that 2.0 is live it'd be good to get started.

**Comment by thisisdano** [comment]
So, it would be great if we could update this to USWDS 2.x.

Beyond including the new code and updating the markup, there are a couple additional issues with compiling the Sass from the USWDS source:

1. Jekyll's native Sass compiling is not sufficient to process USWDS 2.x Sass
1. USWDS Sass need to be both **autoprefixed** and have its **media queries grouped** per https://v2.designsystem.digital.gov/documentation/developers/#sass-compilation-requirements (with something like https://github.com/aaronjensen/sass-media_query_combiner)
1. It should probably also be minified

So there'll need to be a new Sass pipeline to handle these requirements. But if we can sort that out, most of the rest of the update should be straightforward.

**Comment by blacktm** [comment]
Hi all, I spoke with @thisisdano about this and will be taking it on. No timeline yet, but we're getting started now. Just wanted to 🚩.

**Comment by BryanSchuetz** [comment]
@blacktm I'd be happy to help out with this—would be nice to be able to use V2 here.

**Comment by blacktm** [comment]
Awesome @BryanSchuetz, thanks for the offer! I've mostly handed things back over to @thisisdano, and I think he's pretty close to finishing.

**Comment by thisisdano** [comment]
Yup — It's close. I expect to finish code and documentation next week

**Comment by arivers** [comment]
Any updates on this? I see there was aa commit on 1/10/2020 to the 2.0 branch.

**Comment by afeld** [comment]
USWDS 2.0 support has been released with the `uswds-jekyll` 5.0.0 🎉 🎉 5️⃣ 🎉 🎉  Check out the [migration guide](https://github.com/18F/uswds-jekyll#migrating-from-earlier-versions).

This was over a year of work; kudos to @thisisdano @blacktm @hoaiandang and others on it!
