### ISSUE TITLE
Make Esc key close menu item for desktop version of the site

### ISSUE THREAD

**Issue by whit1206** [18F/uswds-jekyll#177]
This is a great project and looks and works well! It would be helpful if the Esc key could be used to collapse an expanded main menu item when on the full width (desktop) version of the site. It currently works for the mobile version of the menu but not full width.

Example:
<img width="330" alt="Screen Shot 2019-06-11 at 11 04 06 AM" src="https://user-images.githubusercontent.com/1154685/59295519-c30d5980-8c38-11e9-8fdf-9541d1df699c.png">

**Comment by aduth** [comment]
Since this behavior is inherited from [U.S. Web Design System](https://github.com/uswds/uswds), it might make sense to report the issue there.

Note the same issue, but related: https://github.com/uswds/uswds/issues/3528

**Comment by afeld** [comment]
This project is in maintenance mode, so closing.
