### ISSUE TITLE
support Jekyll 4

### ISSUE THREAD

**Issue by afeld** [18F/uswds-jekyll#181]
Jekyll 4 has performance improvements, and:

> Developers may now bundle a config.yml into their theme-gem to provide some boilerplate configurations for the theme.

https://jekyllrb.com/news/2019/08/20/jekyll-4-0-0-released/

I've only read that part, so not sure what's needed in terms of this project to leverage that.

**Comment by thisisdano** [comment]
Seems like it could be useful
