### ISSUE TITLE
Search Form in extended header is not visible

### ISSUE THREAD

**Issue by davemcorwin** [18F/uswds-jekyll#184]
The search form in the `extended` and `extended-mega` headers includes a class of `usa-sr-only` hiding the entire form, including the input field from view for browser users.

This is not the case in the other header types, Is this intentional?

Removing this class results in expected behavior when using a browser.

Viewed in Chrome.
 
See https://github.com/18F/uswds-jekyll/blob/master/_includes/components/header.html#L111

**Comment by afeld** [comment]
Fixed in #180. Want to give it a review?

**Comment by rahearn** [comment]
Should be fixed via #180. Please re-open if not.
