### ISSUE TITLE
Consider default value "#top" for data.footer.top.href

### ISSUE THREAD

**Issue by aduth** [18F/uswds-jekyll#191]
The default configuration provided for `data.footer.top.href` assigns a value of `#` to use as the `href` for the "Back to Top" link:

https://github.com/18F/uswds-jekyll/blob/472991d0f798968dfc0fb4f7c096a0061f89f8cd/_data/footer.yml#L8-L13

As observed at https://github.com/18F/development-guide/pull/172 (and previously addressed at https://github.com/18F/development-guide/pull/130), this can cause errors to be flagged when using [`html-proofer`](https://github.com/gjtorikian/html-proofer), since it marks these fragments as invalid (see also https://github.com/gjtorikian/html-proofer/issues/118).

An enhancement to `html-proofer` to allow `#top` fragment was proposed at https://github.com/gjtorikian/html-proofer/pull/421 by @afeld and subsequently merged. As noted there, `#top` is a valid indicator for "top of the document". Since it's considered valid both by the HTML specification and by `html-proofer`, it may be a more sensible default to provide in this configuration.

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
