### ISSUE TITLE
Update to latest USWDS (2.8.0)

### ISSUE THREAD

**Issue by thisisdano** [18F/uswds-jekyll#192]
We'll want to update this to 2.8.0, as well as assuring that any new assets are included, and that we update new or updated components since the last update:

- Banner
- Breadcrumb
- Button group
- Card
- Character count
- Date picker
- Date range picker
- File input
- Tooltip

This will also require adding an autoprefixer to the build, as referenced here: https://designsystem.digital.gov/documentation/developers/#sass-compilation-requirements

https://github.com/vwochnik/jekyll-autoprefixer could be a good bet.

**Comment by pkarman** [comment]
Could the README also change to refer to the `master` branch instead of the once-deleted-now-restored-but-inevitably-nonpermanent `update-uswds-2.0` branch?

**Comment by afeld** [comment]
@hoaiandang Mind fixing the README to direct people to use the released version rather than pointing to GitHub?

**Comment by ryanwoldatwork** [comment]
This updates to 2.8.1. https://github.com/18F/uswds-jekyll/pull/207

**Comment by ryanwoldatwork** [comment]
I do think a conversation about whether to include all the USWDS source, unpacked, as part of this .gem is the right move or not. This upgrade included copying all the USWDS `_sass` assets into this project, as well as the final .css. I'm a bit confused as which to use, especially when including this .gem in another Jekyll project.

**Comment by afeld** [comment]
Upgraded to 2.9.0 in https://github.com/18F/uswds-jekyll/pull/210.
