### ISSUE TITLE
add tips on how to not upgrade

### ISSUE THREAD

**Issue by afeld** [18F/uswds-jekyll#193]
A user (friend of the show, thankfully) [pointed out](https://twitter.com/MarinaNitze/status/1290852968099483648) that their site unexpectedly broke when using uswds-jekyll as a remote theme. Let's include a section in the migration guide about how to lock to a previous version, whether someone is using a Gemfile or a [remote theme](https://github.com/benbalter/jekyll-remote-theme#declaring-your-theme).

While we're at it, let's add a message at the top of the README about "5.0 was released with breaking changes—see the migration guide."

## Acceptance criteria

- There are clear instructions about how to avoid using the latest versions of the theme

**Comment by its-a-lisa-at-work** [comment]
@afeld should this stay on our board? If so, are we the owners of this repo? Otherwise, I would maybe transfer this to our repo unless it needs to stay in this repo

**Comment by afeld** [comment]
> are we the owners of this repo?

https://github.com/18F/tts-tech-portfolio/pull/699

**Comment by afeld** [comment]
Closing as stale.
