### ISSUE TITLE
Side navigation isn't working as it should

### ISSUE THREAD

**Issue by hoaiandang** [18F/uswds-jekyll#195]
Sub-options within the sidebar that links to pages doesn't show up.

Given the following navigation settings:
<img width="351" alt="Screen Shot 2020-08-07 at 11 53 11 AM" src="https://user-images.githubusercontent.com/32590271/89678868-c9cb4700-d8a4-11ea-8873-8546826e5cf8.png">

The theme outputs the following sidebar:
<img width="321" alt="Screen Shot 2020-08-07 at 11 52 55 AM" src="https://user-images.githubusercontent.com/32590271/89678792-aaccb500-d8a4-11ea-9616-74c60eae8352.png">

Demo link A, Demo link B, and Demo link C are missing

**Comment by ryanhofdotgov** [comment]
See #202 – I think this is just bad example data. The sidenav doesn't work that way and would conflict with the subnav feature.

**Comment by ryanhofdotgov** [comment]
Fixed in #202
