### ISSUE TITLE
v5.0.0 not marked as a release

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/uswds-jekyll#199]
The v5.0.0 tag doesn't have [an associated release](https://github.com/18F/uswds-jekyll/releases), so the sidebar on the front page of this repo still reports that v4.2.0 is the latest release.

Just looking at #178 and the Slack announcement, I took a stab at release notes:

A major release incorporating [USWDS 2](https://designsystem.digital.gov/whats-new/updates/2019/04/08/introducing-uswds-2-0/). Check out the [migration guide](https://github.com/18F/uswds-jekyll#migrating-from-earlier-versions) to update your site from earlier `uswds-jekyll` releases. 

## Added
- Use [Prettier](https://prettier.io/) for consistent formatting
- New `sidenav-breakpoint` key in `navigation.yml`
- New color configuration keys in `theme.yml`

## Updated
- USWDS to [2.7.0](https://designsystem.digital.gov/about/releases/#version-270) from USWDS [1.6.9](https://designsystem.digital.gov/about/releases/#version-169) – and all HTML templates and layouts to match
- Jekyll to [4.0](https://jekyllrb.com/news/2019/08/20/jekyll-4-0-0-released/)
- Renamed  footer type `medium` to `default` in `footer.yml`
- Reorganized `_sass` directory layout
- Disabled search by default

**Comment by afeld** [comment]
Thanks! Added.
