### ISSUE TITLE
Add support for DAP subagency in v4.x line

### ISSUE THREAD

**Issue by davemcorwin** [18F/uswds-jekyll#209]
## Background information

Per the digital council, all TTS web properties should include a DAP configuration with the subagency field containing a value that includes `TTS`. The ability to configure this in `_config.yml` has been added to the v5.x line of releases but not to previous versions. Consumers of this library may want this feature without upgrading to v5 which requires upgrading the USWDS v2, a potentially non-trivial change.

## Acceptance criteria

- v4.x version that includes the ability to configure the subagency for DAP

## Complications
There is currently no long-lived branch representing the 4.x line so no base branch against which a Pull Request can been created. That said, I pushed up a new branch [`v4.3.0`](https://github.com/18F/uswds-jekyll/tree/v4.3.0) that contains the change, and can potentially be tagged and released.

@afeld thoughts?

**Comment by afeld** [comment]
See my thoughts on it in https://github.com/18F/uswds-jekyll/pull/205#pullrequestreview-488191214. If you feel strongly about backporting support, we can do it.
