### ISSUE TITLE
Identify configurations that seem to be universal across sites that can be set as a default

### ISSUE THREAD

**Issue by hoaiandang** [18F/uswds-jekyll#219]
## Background information

Part of https://github.com/18F/uswds-jekyll/issues/190.

## Acceptance criteria

- We know what configurations we can set as a default to help us make uswds-jekyll more opinionated
---

The assignee should add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by afeld** [comment]
This project is in maintenance mode, so closing.
