### ISSUE TITLE
Use of relative_url is too restrictive

### ISSUE THREAD

**Issue by konklone** [18F/uswds-jekyll#27]
I'd like to use external URLs in a few places - the secondary nav, the footer, and other places where the components enforce a processor of `relative_url`. 

Would there be any significant issue with removing it? I _think_ the intent of `relative_url` is to provide a safe filter on top of potentially hostile user-provided content. However, in this case, the only links getting embedded are ones selected by the site owner in their own data files.

**Comment by line47** [comment]
Hey @konklone I've got an in progress PR to address this if you want to take a look and provide feedback. https://github.com/18F/uswds-jekyll/pull/28
