### ISSUE TITLE
Extra pipe `|` showing in header-extended when only search is present

### ISSUE THREAD

**Issue by line47** [18F/uswds-jekyll#46]
When search is the only item in the header there is an empty `<li>` generated which causes a `|` to be added after the search. [header--extended.html](https://github.com/18F/uswds-jekyll/blob/master/_includes/components/header--extended.html#L72) is where this functionality lives.

### Screenshots
![screen shot 2017-09-26 at 11 14 01 am](https://user-images.githubusercontent.com/1449852/30868171-ddc01484-a2ab-11e7-8cd8-fb4a2251b5d2.png)

![screen shot 2017-09-26 at 11 14 24 am](https://user-images.githubusercontent.com/1449852/30868205-f1bb4f12-a2ab-11e7-9d4c-be05a2a0899d.png)

**Comment by line47** [comment]
I think we decided that this was not an issue but a configuration that was causing the issue. Is that what you remember @hursey013 ?

**Comment by hursey013** [comment]
Yeah from my testing if you want only the search box in the secondary nav and do not want the pipe to appear, you would just set the `secondary.links` key in `header.yml` to an empty string. You could also comment out `secondary.links` which would have the same effect. 

The extra pipe only appears when you try and point `secondary.links` to an empty or blank array in `navigation.yml`.
