### ISSUE TITLE
Stylesheets not included properly

### ISSUE THREAD

**Issue by hursey013** [18F/uswds-jekyll#47]
When following the docs on how to include an array of stylesheets: https://github.com/18F/uswds-jekyll#stylesheets I noticed the HTML output was not correct.

To recreate, add the following to `_config.yml`:
```
styles:
  - href: /assets/css/main.css
    media: screen
  - href: /assets/css/print.css
    media: print
```
When the site is generated, this is the HTML that is produced for the YAML above:
```
<link rel="stylesheet"
  href="/%5B%22href%22,%20%22/assets/css/main.css%22%5D"
  media="screen">

<link rel="stylesheet"
  href="/%5B%22media%22,%20%22screen%22%5D"
  media="screen">

<link rel="stylesheet"
  href="/%5B%22href%22,%20%22/assets/css/print.css%22%5D"
  media="screen">

<link rel="stylesheet"
  href="/%5B%22media%22,%20%22print%22%5D"
  media="screen">
```
I would expect the output to be more like this:
```
<link rel="stylesheet"
  href="/assets/css/main.css"
  media="screen">

<link rel="stylesheet"
  href="/assets/css/print.css"
  media="print">
```

I'm testing some fixes and will submit a PR, just wanted to get the issue documented first.

**Comment by line47** [comment]
Fantastic! Thanks for finding this @hursey013 !

**Comment by line47** [comment]
I think this issue can be closed, is that right @hursey013 ?

**Comment by hursey013** [comment]
No, I am experiencing this same issue with the latest version of the gem - it only happens when you try to specify stylesheets using `href` and `media` - I think it has to do with the use of the `uniq` filter. I will submit another PR.

**Comment by line47** [comment]
Looking at this is looks like removing the `| uniq` line in styles.html does the trick

**Comment by hursey013** [comment]
Yeah let me double check on this and will re-open PR if need be.
