### ISSUE TITLE
Do we still need jekyll-uswds.gemspec?

### ISSUE THREAD

**Issue by hursey013** [18F/uswds-jekyll#51]
This file: https://github.com/18F/uswds-jekyll/blob/master/jekyll-uswds.gemspec looks like it's leftover from when the gem used to be called `jekyll-uswds`. I searched through the 18F github (and all of github in fact) to see if there were any repos using that old name and came up empty. In order to avoid confusion in the future, I wonder if we could remove this file at some point?

**Comment by line47** [comment]
I think that it a good idea for sure @hursey013

**Comment by afeld** [comment]
Removed in #58.
