### ISSUE TITLE
Keep tabs on USWDS Federalist template

### ISSUE THREAD

**Issue by hursey013** [18F/uswds-jekyll#54]
When creating a new Federalist site users are given the option to generate the site using a USWDS template which references: https://github.com/18F/federalist-uswds-template, which in turn references this Jekyll theme gem. 

We should establish some sort of workflow that keeps `federalist-uswds-template` in mind since it may occasionally require manually bumping up the version number of this gem in it's gemfile and also keeping in mind that major changes to the config/data files may affect the template repo.

**Comment by afeld** [comment]
Longer discussion about the related themes in https://github.com/18F/guides-template/issues/84.

**Comment by afeld** [comment]
Clarified the relationship in https://github.com/18F/federalist-uswds-jekyll#comparison-with-uswds-jekyll.
