### ISSUE TITLE
Incorporate DigitalGov search option

### ISSUE THREAD

**Issue by line47** [18F/uswds-jekyll#62]
It was noted that a good offer would be to incorporate DigitalGov search as an option to the USWDS-Jekyll as a more robust option to the jekyll_pages_api_search. One minor caveat is that an account would need to be setup with DigitalGov to get search up and running on the site. The benefit would be to have a great live search option with many more features as well as more support.

**Comment by wslack** [comment]
Let's include this as part of the Epic to get USWDS-Jekyll and other templates aligned.

**Comment by line47** [comment]
I'm thinking about abstracting the search code itself from the headers and making it into it's own component that can be included when and where necessary.

**Comment by line47** [comment]
I'm also wondering about putting all of the search configurations in one place currently we have search configs in the `_config.yml` as well as the `header.yml`. 

I think it would be more intuitive to have the necessary configs in the `_config.yml` file as search is a site wide element.

**Comment by wslack** [comment]
Concur; the settings should live in one spot.
