### ISSUE TITLE
Bundling data files in the theme-gem

### ISSUE THREAD

**Issue by ashmaroli** [18F/uswds-jekyll#67]
Currently, if a user creates a brand new Jekyll site and attempts to take the theme-gem for a test-drive, they'll be greeted by an empty page at `http://localhost:4000/`. The reason simply being that the site is tightly dependent on the data files.

If you're up for it, I can send in a PR that bundles the data files into the theme-gem and which can then be read by Jekyll via a plugin called [`jekyll-data`](https://github.com/ashmaroli/jekyll-data).

The first step is to bundle `_data/` within the theme-gem.
The next step can take **either of the following** based on your discretion:
  - **list `jekyll-data` as `runtime_dependency` for the theme-gem.** Users on Jekyll 3.5 and above will automatically load the plugin (and therefore read the bundled data files) when they `build` / `serve` with Jekyll.
  - **recommend the use of `jekyll-data` plugin.** Let the user decide if they want to use a 3rd-party plugin and then add the plugin to their Gemfile (similar to the `jekyll_pages_api_search` plugin)

Either way, the plugin provides a better onboarding for the new user. That said, they'd still need to copy the concerned data file to the source directory for customizing it.

**Comment by wslack** [comment]
@line47 how should this be triaged?

**Comment by adborden** [comment]
To me, the issue here is that `jekyll new` creates a blank site because it requires configuration. I would recommend that instead of bundling the data files, we just make sure some sane defaults are set so that you actually get a default uswds theme.

**Comment by rahearn** [comment]
Since there are a lot of settings (such as navigation) that are rather useless, I think setting sane defaults for a couple things, and gracefully handling more missing configuration is the way to go.

**Comment by adborden** [comment]
Sane defaults would be great.

**Comment by ashmaroli** [comment]
The ecosystem changed quite a bit since the time this ticket was opened. Nowadays, theme developers recommend that their users rely on the [`remote-theme`](https://github.com/benbalter/jekyll-remote-theme) functionality bundled with GitHub Pages to use any theme hosted on GitHub for their project.

That has somewhat reduced the need for my plugin `jekyll-data`. But even then, it has not been obsolete.

However, with Jekyll 4.0 (under development), theme developers will be able to ship a **`_config.yml`** inside their theme-gem which can be used to provide basic defaults. (a feature adapted from `jekyll-data` plugin as well)

**Comment by afeld** [comment]
Closing in favor of https://github.com/18F/uswds-jekyll/issues/190 (having more sane defaults).
