### ISSUE TITLE
Inner page subnav URLs are not correct

### ISSUE THREAD

**Issue by line47** [18F/uswds-jekyll#71]
Currently the code for the on page subnav is 
```HTML
{% for link in include.links %}
  <li>
    <a href="{% if link.external == true %}{{ link.href }}{% else %}{{ link.href | relative_url }}{% endif %}">{{ link.text }}</a>
  </li>
{% endfor %}
```

The `relative_url` portion of the link is not keeping the path and I think needs to be removed.
For example, take a look at https://federalist-proxy.app.cloud.gov/preview/18f/federalist-uswds-template/update-uswds/docs/

The subnav links for **section one** and **section two** do not keep you in the `/docs/` directory. 
### The subnav links are  going here
_Notice no `/docs/` in the URL_

https://federalist-proxy.app.cloud.gov/preview/18f/federalist-uswds-template/update-uswds/#section-one 
### The subnav links should be going here
https://federalist-proxy.app.cloud.gov/preview/18f/federalist-uswds-template/update-uswds/docs/#section-one

**Comment by hursey013** [comment]
Is the expectation that the subnav links will always be anchors?

**Comment by line47** [comment]
That's a good question, and it looks like from the docs that the intent is for it to be internal https://github.com/18F/uswds-jekyll#page-subnavigation

**Comment by hursey013** [comment]
Got it. In that case I don't think `relative_url` is needed. I'll open a PR.
